# WHAT DOES IT MEAN TO HAVE A GOOD LINK?
# 200 on GET REQUEST?

# 0
# WRITE SCRIPT TAKES URL AND RETURNS IF IT'S REACHABLE OR NOT..



# 1
# WRITE SCRIPT TAKES FILE OF URLS AND RETURNS THE REACHABLE ONES..


